[package]
name = "libapplet-launch"
version = "0.1.0"
authors = ["XorTroll"]
edition = "2018"

[dependencies]
nx = { path = "../../../nx" }

[package.metadata.sprinkle.nro]

[package.metadata.sprinkle.nro.nacp]
name = "libapplet-launch"
author = "XorTroll"
version = "Test"